version: "3.7"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    restart: unless-stopped
    ports:
     - "7777:7777"
    volumes: ['./app:/app']
